// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Analizador/Lexer.jflex

package Analizador;

import java_cup.runtime.Symbol;
import Errores.Errores;
import static Func.Function.list;

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\2\1\1\22\0\1\3\1\0\1\4"+
    "\5\0\1\5\1\6\2\0\1\7\1\10\1\11\1\0"+
    "\12\12\1\13\1\14\1\15\3\0\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\2\24"+
    "\1\30\1\31\1\32\1\33\1\34\1\24\1\35\1\36"+
    "\1\24\1\37\1\40\1\24\1\41\1\24\1\42\1\43"+
    "\1\0\1\44\3\0\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\24\1\30\1\31\1\32"+
    "\1\33\1\34\1\24\1\35\1\36\1\24\1\37\1\40"+
    "\1\24\1\41\1\24\1\42\1\0\1\1\10\0\1\2"+
    "\252\0\2\45\115\0\1\46\u01a8\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\2\1\1\3\1\4\1\5\1\6\1\7"+
    "\1\2\1\10\1\11\2\2\12\12\1\13\1\14\1\2"+
    "\1\7\2\0\1\15\1\16\1\17\5\12\1\0\11\12"+
    "\1\0\1\20\1\17\1\21\1\12\1\22\1\12\1\22"+
    "\1\23\1\24\1\12\1\25\1\26\1\12\2\27\1\30"+
    "\1\31\1\30\2\12\1\7\1\12\1\0\1\32\2\12"+
    "\2\0\1\12\1\7\2\33\2\12\1\0\1\34\1\35"+
    "\1\7\1\12\1\0\2\12\1\0\1\7\2\36\1\37"+
    "\1\12\1\0\1\7\2\40\2\7\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\47\0\47\0\47\0\47"+
    "\0\234\0\303\0\352\0\47\0\u0111\0\u0138\0\u015f\0\u0186"+
    "\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297\0\u02be"+
    "\0\47\0\47\0\u02e5\0\u030c\0\u0333\0\303\0\47\0\47"+
    "\0\u035a\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b"+
    "\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c\0\u05a3"+
    "\0\u05ca\0\u0333\0\u05f1\0\u0186\0\u0618\0\u0186\0\u063f\0\47"+
    "\0\u0666\0\u0186\0\u068d\0\u06b4\0\u0186\0\u06db\0\u0186\0\47"+
    "\0\u0186\0\u0702\0\47\0\u0729\0\u0750\0\u0777\0\u079e\0\u07c5"+
    "\0\u0186\0\u07ec\0\u0813\0\u083a\0\u0861\0\u0888\0\u08af\0\u08d6"+
    "\0\u08fd\0\u0924\0\u094b\0\u0972\0\47\0\u0186\0\u0999\0\u09c0"+
    "\0\u09e7\0\u0a0e\0\u0a35\0\u0a5c\0\u0a83\0\u0186\0\47\0\u0186"+
    "\0\u0aaa\0\u0ad1\0\u0af8\0\u0186\0\47\0\u0b1f\0\u0b46\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\2\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\5\20\1\24\2\20\1\25"+
    "\1\26\1\27\1\20\1\30\2\20\1\31\1\32\1\2"+
    "\1\33\50\0\1\3\1\0\1\3\44\0\1\3\1\0"+
    "\1\4\5\0\1\11\1\34\4\0\24\11\7\0\1\11"+
    "\5\0\1\11\1\34\4\0\24\11\15\0\1\35\1\36"+
    "\47\0\1\37\43\0\1\40\55\0\24\41\7\0\1\11"+
    "\5\0\1\11\1\42\4\0\16\20\1\43\5\20\7\0"+
    "\1\11\5\0\1\11\1\42\4\0\24\20\7\0\1\11"+
    "\5\0\1\11\1\42\4\0\7\20\1\44\14\20\7\0"+
    "\1\11\5\0\1\11\1\42\4\0\10\20\1\45\3\20"+
    "\1\46\7\20\2\0\1\47\4\0\1\11\5\0\1\11"+
    "\1\42\4\0\13\20\1\50\10\20\7\0\1\11\5\0"+
    "\1\11\1\42\4\0\1\51\3\20\1\52\7\20\1\53"+
    "\3\20\1\54\3\20\7\0\1\11\5\0\1\11\1\42"+
    "\4\0\16\20\1\55\5\20\7\0\1\11\5\0\1\11"+
    "\1\42\4\0\4\20\1\56\17\20\7\0\1\11\5\0"+
    "\1\11\1\42\4\0\20\20\1\57\3\20\7\0\1\11"+
    "\5\0\1\11\1\42\4\0\1\60\23\20\43\0\1\61"+
    "\21\0\1\34\46\0\1\62\46\0\1\63\4\0\24\41"+
    "\16\0\1\42\37\0\1\11\5\0\1\11\1\42\4\0"+
    "\16\20\1\64\5\20\7\0\1\11\5\0\1\11\1\42"+
    "\4\0\1\65\23\20\7\0\1\11\5\0\1\11\1\42"+
    "\4\0\21\20\1\66\2\20\7\0\1\11\5\0\1\11"+
    "\1\42\4\0\20\20\1\67\3\20\44\0\1\70\11\0"+
    "\1\11\5\0\1\11\1\42\4\0\3\20\1\71\20\20"+
    "\7\0\1\11\5\0\1\11\1\42\4\0\22\20\1\72"+
    "\1\20\7\0\1\11\5\0\1\11\1\42\4\0\3\20"+
    "\1\73\20\20\7\0\1\11\5\0\1\11\1\42\4\0"+
    "\3\20\1\74\20\20\7\0\1\11\5\0\1\11\1\42"+
    "\4\0\11\20\1\75\12\20\7\0\1\11\5\0\1\11"+
    "\1\42\4\0\14\20\1\76\7\20\7\0\1\11\5\0"+
    "\1\11\1\42\4\0\17\20\1\77\4\20\3\0\1\100"+
    "\3\0\1\11\5\0\1\11\1\42\4\0\12\20\1\101"+
    "\11\20\7\0\1\11\5\0\1\11\1\42\4\0\16\20"+
    "\1\102\5\20\35\0\1\103\27\0\1\63\37\0\1\11"+
    "\5\0\1\11\1\42\4\0\16\20\1\104\5\20\7\0"+
    "\1\11\5\0\1\11\1\42\4\0\1\20\1\105\22\20"+
    "\7\0\1\106\5\0\1\11\1\42\4\0\24\20\7\0"+
    "\1\11\5\0\1\11\1\42\4\0\10\20\1\107\13\20"+
    "\2\0\1\110\4\0\1\11\5\0\1\11\1\42\4\0"+
    "\1\111\23\20\7\0\1\11\5\0\1\11\1\42\4\0"+
    "\6\20\1\112\15\20\7\0\1\11\5\0\1\11\1\42"+
    "\4\0\10\20\1\113\13\20\2\0\1\114\4\0\1\11"+
    "\5\0\1\11\1\42\4\0\24\20\1\115\6\0\1\11"+
    "\5\0\1\11\1\42\4\0\11\20\1\116\12\20\7\0"+
    "\1\11\5\0\1\11\1\34\4\0\15\11\1\117\6\11"+
    "\7\0\1\11\5\0\1\11\1\42\4\0\1\120\23\20"+
    "\23\0\1\121\32\0\1\11\5\0\1\11\1\42\4\0"+
    "\16\20\1\122\5\20\7\0\1\11\5\0\1\11\1\42"+
    "\4\0\1\123\23\20\23\0\1\124\73\0\1\125\5\0"+
    "\1\11\5\0\1\11\1\42\4\0\4\20\1\126\17\20"+
    "\7\0\1\11\5\0\1\11\1\34\4\0\16\11\1\127"+
    "\5\11\7\0\1\11\5\0\1\11\1\42\4\0\13\20"+
    "\1\130\10\20\36\0\1\131\17\0\1\11\5\0\1\11"+
    "\1\42\4\0\1\132\23\20\7\0\1\11\5\0\1\11"+
    "\1\42\4\0\13\20\1\133\10\20\36\0\1\134\17\0"+
    "\1\11\5\0\1\11\1\34\4\0\14\11\1\135\7\11"+
    "\7\0\1\11\5\0\1\11\1\42\4\0\1\136\23\20"+
    "\23\0\1\137\32\0\1\11\5\0\1\11\1\42\4\0"+
    "\12\20\1\140\11\20\7\0\1\11\5\0\1\11\1\42"+
    "\4\0\23\20\1\141\46\0\1\142\7\0\1\11\5\0"+
    "\1\11\1\34\4\0\6\11\1\143\15\11\7\0\1\11"+
    "\5\0\1\11\1\42\4\0\1\144\23\20\23\0\1\145"+
    "\32\0\1\11\5\0\1\11\1\34\4\0\16\11\1\146"+
    "\5\11\7\0\1\11\5\0\1\11\1\34\4\0\1\147"+
    "\23\11\7\0\1\11\5\0\1\11\1\34\4\0\12\11"+
    "\1\150\11\11\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2925];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\2\1\4\11\3\1\1\11\14\1\2\11"+
    "\2\1\2\0\2\11\6\1\1\0\11\1\1\0\6\1"+
    "\1\11\7\1\1\11\2\1\1\11\4\1\1\0\3\1"+
    "\2\0\6\1\1\0\1\11\3\1\1\0\2\1\1\0"+
    "\2\1\1\11\2\1\1\0\2\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignore */
            }
          // fall through
          case 34: break;
          case 2:
            { //System.err.println("warning:Unrecognized character - "+yytext());
    Errores Error = new Errores(yyline,yycolumn,yytext(),"lexico");
    list.add(Error);
    //list_errores.add(Errores);
    //System.out.println(Error.toString());
            }
          // fall through
          case 35: break;
          case 3:
            { return new Symbol(sym.COMI, yyline, yycolumn, yytext());
            }
          // fall through
          case 36: break;
          case 4:
            { return new Symbol(sym.PARIZQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 37: break;
          case 5:
            { return new Symbol(sym.PARDER, yyline, yycolumn, yytext());
            }
          // fall through
          case 38: break;
          case 6:
            { return new Symbol(sym.COMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 39: break;
          case 7:
            { return new Symbol(sym.CADENA, yyline, yycolumn, yytext());
            }
          // fall through
          case 40: break;
          case 8:
            { return new Symbol(sym.DP, yyline, yycolumn, yytext());
            }
          // fall through
          case 41: break;
          case 9:
            { return new Symbol(sym.PYC, yyline, yycolumn, yytext());
            }
          // fall through
          case 42: break;
          case 10:
            { return new Symbol(sym.ID, yyline, yycolumn, yytext());
            }
          // fall through
          case 43: break;
          case 11:
            { return new Symbol(sym.CORIZQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 44: break;
          case 12:
            { return new Symbol(sym.CORDER, yyline, yycolumn, yytext());
            }
          // fall through
          case 45: break;
          case 13:
            { return new Symbol(sym.DPD, yyline, yycolumn, yytext());
            }
          // fall through
          case 46: break;
          case 14:
            { return new Symbol(sym.FLIZQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 47: break;
          case 15:
            { return new Symbol(sym.IDARR, yyline, yycolumn, yytext());
            }
          // fall through
          case 48: break;
          case 16:
            { return new Symbol(sym.NUM, yyline, yycolumn, yytext());
            }
          // fall through
          case 49: break;
          case 17:
            { return new Symbol(sym.ARRAY, yyline, yycolumn, yytext());
            }
          // fall through
          case 50: break;
          case 18:
            { return new Symbol(sym.DIV, yyline, yycolumn, yytext());
            }
          // fall through
          case 51: break;
          case 19:
            { return new Symbol(sym.END, yyline, yycolumn, yytext());
            }
          // fall through
          case 52: break;
          case 20:
            { return new Symbol(sym.MAX,yyline, yycolumn, yytext());
            }
          // fall through
          case 53: break;
          case 21:
            { return new Symbol(sym.MOD, yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 22:
            { return new Symbol(sym.MULTI, yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 23:
            { return new Symbol(sym.RESTA, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 24:
            { return new Symbol(sym.SUM, yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 25:
            { return new Symbol(sym.VAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 26:
            { return new Symbol(sym.MODA, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 27:
            { return new Symbol(sym.MEDIA, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 28:
            { return new Symbol(sym.CHAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 29:
            { return new Symbol(sym.DOUBLE, yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 30:
            { return new Symbol(sym.MEDIANA, yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 31:
            { return new Symbol(sym.PROGRAM, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 32:
            { return new Symbol(sym.VARIANZA, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 33:
            { return new Symbol(sym.ENDP, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
