
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 3;
  public static final int CONSO = 34;
  public static final int DOUBLE = 4;
  public static final int RESTA = 22;
  public static final int ARRAY = 17;
  public static final int ENDP = 12;
  public static final int DPD = 9;
  public static final int CORDER = 20;
  public static final int FLIZQ = 5;
  public static final int DIV = 26;
  public static final int NUM = 15;
  public static final int IG = 36;
  public static final int MIN = 33;
  public static final int ID = 10;
  public static final int MEDIANA = 30;
  public static final int EOF = 0;
  public static final int PARIZQ = 23;
  public static final int error = 1;
  public static final int PROGRAM = 14;
  public static final int COMA = 8;
  public static final int CADENA = 16;
  public static final int MODA = 29;
  public static final int MOD = 27;
  public static final int COLUM = 37;
  public static final int FLDER = 6;
  public static final int IDARR = 18;
  public static final int VARIANZA = 31;
  public static final int END = 2;
  public static final int MULTI = 25;
  public static final int SUM = 21;
  public static final int MEDIA = 28;
  public static final int PARDER = 24;
  public static final int CORIZQ = 19;
  public static final int MAX = 32;
  public static final int VAR = 13;
  public static final int DP = 7;
  public static final int PRINT = 35;
  public static final int PYC = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "END",
  "CHAR",
  "DOUBLE",
  "FLIZQ",
  "FLDER",
  "DP",
  "COMA",
  "DPD",
  "ID",
  "PYC",
  "ENDP",
  "VAR",
  "PROGRAM",
  "NUM",
  "CADENA",
  "ARRAY",
  "IDARR",
  "CORIZQ",
  "CORDER",
  "SUM",
  "RESTA",
  "PARIZQ",
  "PARDER",
  "MULTI",
  "DIV",
  "MOD",
  "MEDIA",
  "MODA",
  "MEDIANA",
  "VARIANZA",
  "MAX",
  "MIN",
  "CONSO",
  "PRINT",
  "IG",
  "COLUM"
  };
}

