
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 15;
  public static final int NUM = 14;
  public static final int PROGRAM = 13;
  public static final int FLIZQ = 5;
  public static final int EOF = 0;
  public static final int VAR = 11;
  public static final int PYC = 9;
  public static final int DOUBLE = 4;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int COMI = 12;
  public static final int ENDP = 10;
  public static final int DP = 6;
  public static final int END = 2;
  public static final int CHAR = 3;
  public static final int DPD = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "END",
  "CHAR",
  "DOUBLE",
  "FLIZQ",
  "DP",
  "DPD",
  "ID",
  "PYC",
  "ENDP",
  "VAR",
  "COMI",
  "PROGRAM",
  "NUM",
  "CADENA"
  };
}

